name: Coverage report

on:
  push:
    branches: 
      - 'main'
      - 'dev'
  pull_request:
    branches: 
      - 'main'
      - 'dev'
jobs:
  coverage:
    runs-on: ubuntu-latest
    env:
      RUSTUP_TOOLCHAIN: stable
      LLVM_PROFILE_FILE: "LLY-DML-%p-%m.profraw"
      RUSTFLAGS: "-Cinstrument-coverage"

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: llvm-tools-preview

      - name: Install dependencies
        run: |
          python -m pip install -r requirements.txt
          cargo install grcov
          sudo apt-get install lcov

      - name: Run Python tests and collect coverage
        run: pytest --cov=lly_dml

      - name: Run Rust tests and collect coverage
        run: |
          cargo test --verbose
          grcov . --binary-path target/debug/ --source-dir . --output-type lcov --output-path rust.info --llvm --branch --parallel --keep-only 'src/*'

      - name: Combine Python and Rust coverage
        run: |
          coverage combine
          coverage lcov -o python.info
          lcov --add-tracefile python.info --add-tracefile rust.info --output-file coveralls.info

      - name: Upload to Coveralls
        uses: coverallsapp/github-action@v2.3.4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: coveralls.info
