name: Miri

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev
concurrency:
  group: ${{ github.repository }}-${{ github.ref }}-${{ github.head_ref }}-${{ github.workflow }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  miri:
    if: github.repository_owner == 'LILY-QML'
    name: Miri
    runs-on: ubuntu-latest
    env:
      RUSTUP_TOOLCHAIN: nightly-2024-05-24

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly-2024-05-24
          components: miri

      - name: Prepare Miri
        run: |
          set -e
          # Patch known dependencies to make them Miri-compatible.
          cat >>Cargo.toml <<EOF

          [patch.crates-io]
          crossbeam-epoch = { git = "https://github.com/crossbeam-rs/crossbeam", rev = "9e859610" }
          EOF
          cargo miri setup

      - name: Run Miri
        run: cargo miri test
        env:
          MIRIFLAGS: '-Zmiri-tree-borrows -Zmiri-symbolic-alignment-check -Zmiri-strict-provenance'
