name: QPY Compatibility Tests

on:
  push:
    branches:
      - 'main'
      - 'dev'
  pull_request:
    branches:
      - 'main'
      - 'dev'
concurrency:
  group: ${{ github.repository }}-${{ github.ref }}-${{ github.head_ref }}-${{ github.workflow }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  backward_compat:
    if: github.repository_owner == 'LILY-QML'
    name: Backward Compatibility for QPY
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - uses: actions/checkout@v4

      # Step 2: Set up Python environment
      - uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      # Step 3: Set up Rust toolchain (if your project uses Rust-based extensions)
      - uses: dtolnay/rust-toolchain@stable

      # Step 4: Use caching for test data
      - uses: actions/cache@v4
        with:
          path: test/qpy_compat/qpy_cache
          key: qpy-${{ hashFiles('test/qpy_compat/**') }}

      # Step 5: Run QPY backward compatibility tests
      - name: Run QPY Backward Compatibility Tests
        working-directory: test/qpy_compat
        run: ./run_tests.sh
